runtime: python39
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "authentication-d6496-firebase-adminsdk-zoywr-32ecaa91eb.json"

instance_class: F2  # This defines the type of instance (F2 is for low-traffic apps)