runtime: python39
entrypoint: gunicorn -b :$PORT motor:app  # Replace `motor` with the name of your Python file

service: motor-eval  # This makes sure the service has a unique name
env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "authentication-d6496-firebase-adminsdk-zoywr-32ecaa91eb.json"

instance_class: F2  # Set the instance class
